/* Generated by re2c 0.14.3 on Fri Aug  2 12:08:15 2019 */
#line 1 "src/FuelScanner.r2c"

/*
 * This file is part of gas
 *
 * Copyright (C) 2017 aaron andersen <aaron@fosslib.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "FuelScanner.hpp"
#include "FuelParser.hpp"

namespace ehb
{
    int FuelScanner::scan(std::string* yylval)
    {
#define YYCTYPE char
#define YYCURSOR cursor
#define YYLIMIT limit
#define YYMARKER marker
#define YYFILL(n)

#define yytext std::string(start, cursor - start)

        while (1)
        {
            const char* start = cursor;

            if (state.empty())
            {
                /*
                 * HACK: line 35 of ui/interfaces/backend/console_output/console_output.gas: [t:window;n:rollover_console]
                 * there is a typo here as the ';' should be a ','
                 */

#line 51 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                {
                    unsigned char yych;

                    if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
                    yych = *YYCURSOR;
                    if (yych <= ':')
                    {
                        if (yych <= ' ')
                        {
                            if (yych <= '\n')
                            {
                                if (yych <= 0x00) goto yy27;
                                if (yych <= 0x08) goto yy29;
                                if (yych <= '\t') goto yy22;
                                goto yy24;
                            }
                            else
                            {
                                if (yych == '\r') goto yy22;
                                if (yych <= 0x1F) goto yy29;
                                goto yy22;
                            }
                        }
                        else
                        {
                            if (yych <= ',')
                            {
                                if (yych == '*') goto yy20;
                                if (yych <= '+') goto yy29;
                                goto yy14;
                            }
                            else
                            {
                                if (yych == '/') goto yy2;
                                if (yych <= '9') goto yy20;
                                goto yy12;
                            }
                        }
                    }
                    else
                    {
                        if (yych <= ']')
                        {
                            if (yych <= '@')
                            {
                                if (yych <= ';') goto yy16;
                                if (yych == '=') goto yy18;
                                goto yy29;
                            }
                            else
                            {
                                if (yych <= 'Z') goto yy20;
                                if (yych <= '[') goto yy4;
                                if (yych <= '\\') goto yy29;
                                goto yy6;
                            }
                        }
                        else
                        {
                            if (yych <= 'z')
                            {
                                if (yych == '_') goto yy20;
                                if (yych <= '`') goto yy29;
                                goto yy20;
                            }
                            else
                            {
                                if (yych <= '{') goto yy8;
                                if (yych == '}') goto yy10;
                                goto yy29;
                            }
                        }
                    }
                yy2:
                    yych = *++YYCURSOR;
                    if (yych == '*') goto yy34;
                    if (yych == '/') goto yy36;
                yy3 :
#line 70 "src/FuelScanner.r2c"
                {
                    std::cerr << "unexpected character found: '" << start[0] << "' (" << static_cast<int>(start[0]) << ")" << std::endl;
                    return 0;
                }
#line 111 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy4:
                    ++YYCURSOR;
#line 53 "src/FuelScanner.r2c"
                    {
                        return '[';
                    }
#line 116 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy6:
                    ++YYCURSOR;
#line 54 "src/FuelScanner.r2c"
                    {
                        return ']';
                    }
#line 121 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy8:
                    ++YYCURSOR;
#line 55 "src/FuelScanner.r2c"
                    {
                        return '{';
                    }
#line 126 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy10:
                    ++YYCURSOR;
#line 56 "src/FuelScanner.r2c"
                    {
                        return '}';
                    }
#line 131 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy12:
                    ++YYCURSOR;
#line 57 "src/FuelScanner.r2c"
                    {
                        return ':';
                    }
#line 136 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy14:
                    ++YYCURSOR;
#line 58 "src/FuelScanner.r2c"
                    {
                        return ',';
                    }
#line 141 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy16:
                    ++YYCURSOR;
#line 59 "src/FuelScanner.r2c"
                    {
                        return ',';
                    }
#line 146 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy18:
                    ++YYCURSOR;
#line 61 "src/FuelScanner.r2c"
                    {
                        state.push(expression_statement);
                        return '=';
                    }
#line 151 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy20:
                    ++YYCURSOR;
                    yych = *YYCURSOR;
                    goto yy33;
                yy21 :
#line 63 "src/FuelScanner.r2c"
                {
                    return (*yylval = yytext, FuelParser::token::Identifier);
                }
#line 159 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy22:
                    ++YYCURSOR;
                    yych = *YYCURSOR;
                    goto yy31;
                yy23 :
#line 65 "src/FuelScanner.r2c"
                {
                    continue;
                }
#line 167 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy24:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                    if (yych == '\n') goto yy24;
#line 66 "src/FuelScanner.r2c"
                    {
                        continue;
                    }
#line 175 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy27:
                    ++YYCURSOR;
#line 68 "src/FuelScanner.r2c"
                    {
                        return 0;
                    }
#line 180 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy29:
                    yych = *++YYCURSOR;
                    goto yy3;
                yy30:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                yy31:
                    if (yych <= '\f')
                    {
                        if (yych == '\t') goto yy30;
                        goto yy23;
                    }
                    else
                    {
                        if (yych <= '\r') goto yy30;
                        if (yych == ' ') goto yy30;
                        goto yy23;
                    }
                yy32:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                yy33:
                    if (yych <= '9')
                    {
                        if (yych <= ',')
                        {
                            if (yych == '*') goto yy32;
                            goto yy21;
                        }
                        else
                        {
                            if (yych == '/') goto yy21;
                            goto yy32;
                        }
                    }
                    else
                    {
                        if (yych <= '^')
                        {
                            if (yych <= '@') goto yy21;
                            if (yych <= 'Z') goto yy32;
                            goto yy21;
                        }
                        else
                        {
                            if (yych == '`') goto yy21;
                            if (yych <= 'z') goto yy32;
                            goto yy21;
                        }
                    }
                yy34:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                    if (yych == '*') goto yy39;
                    goto yy34;
                yy36:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                    if (yych <= '\n')
                    {
                        if (yych <= 0x00) goto yy38;
                        if (yych <= '\t') goto yy36;
                    }
                    else
                    {
                        if (yych != '\r') goto yy36;
                    }
                yy38 :
#line 50 "src/FuelScanner.r2c"
                {
                    continue;
                }
#line 240 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy39:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                    if (yych != '/') goto yy34;
                    ++YYCURSOR;
#line 51 "src/FuelScanner.r2c"
                    {
                        continue;
                    }
#line 249 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                }
#line 71 "src/FuelScanner.r2c"
            }
            else if (state.top() == embedded_statement)
            {

#line 257 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                {
                    unsigned char yych;
                    if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
                    yych = *YYCURSOR;
                    if (yych <= 0x1F)
                    {
                        if (yych <= '\n')
                        {
                            if (yych <= 0x08) goto yy50;
                            if (yych <= '\t') goto yy47;
                            goto yy49;
                        }
                        else
                        {
                            if (yych == '\r') goto yy47;
                            goto yy50;
                        }
                    }
                    else
                    {
                        if (yych <= '/')
                        {
                            if (yych <= ' ') goto yy47;
                            if (yych <= '.') goto yy50;
                        }
                        else
                        {
                            if (yych == ']') goto yy46;
                            goto yy50;
                        }
                    }
                    ++YYCURSOR;
                    if ((yych = *YYCURSOR) == '/') goto yy53;
                yy45 :
#line 80 "src/FuelScanner.r2c"
                {
                    return (*yylval = yytext, FuelParser::token::Expression);
                }
#line 285 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy46:
                    yych = *++YYCURSOR;
                    if (yych == ']') goto yy51;
                    goto yy45;
                yy47:
                    ++YYCURSOR;
                yy48 :
#line 79 "src/FuelScanner.r2c"
                {
                    return (*yylval = yytext, FuelParser::token::Expression);
                }
#line 295 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy49:
                    yych = *++YYCURSOR;
                    goto yy48;
                yy50:
                    yych = *++YYCURSOR;
                    goto yy45;
                yy51:
                    ++YYCURSOR;
#line 78 "src/FuelScanner.r2c"
                    {
                        state.pop();
                        return (*yylval = yytext, FuelParser::token::Expression);
                    }
#line 306 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy53:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                    if (yych <= '\n')
                    {
                        if (yych <= 0x00) goto yy55;
                        if (yych <= '\t') goto yy53;
                    }
                    else
                    {
                        if (yych != '\r') goto yy53;
                    }
                yy55 :
#line 77 "src/FuelScanner.r2c"
                {
                    continue;
                }
#line 320 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                }
#line 82 "src/FuelScanner.r2c"
            }
            else if (state.top() == expression_statement)
            {

#line 329 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                {
                    unsigned char yych;
                    if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
                    yych = *YYCURSOR;
                    if (yych <= '!')
                    {
                        if (yych <= '\f')
                        {
                            if (yych <= 0x08) goto yy68;
                            if (yych <= '\t') goto yy65;
                            if (yych <= '\n') goto yy67;
                            goto yy68;
                        }
                        else
                        {
                            if (yych <= '\r') goto yy65;
                            if (yych == ' ') goto yy65;
                            goto yy68;
                        }
                    }
                    else
                    {
                        if (yych <= ':')
                        {
                            if (yych <= '"') goto yy63;
                            if (yych != '/') goto yy68;
                        }
                        else
                        {
                            if (yych <= ';') goto yy60;
                            if (yych == '[') goto yy62;
                            goto yy68;
                        }
                    }
                    ++YYCURSOR;
                    if ((yych = *YYCURSOR) == '/') goto yy71;
                yy59 :
#line 95 "src/FuelScanner.r2c"
                {
                    return (*yylval = yytext, FuelParser::token::Expression);
                }
#line 360 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy60:
                    ++YYCURSOR;
#line 91 "src/FuelScanner.r2c"
                    {
                        state.pop();
                        return ';';
                    }
#line 365 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy62:
                    yych = *++YYCURSOR;
                    if (yych == '[') goto yy69;
                    goto yy59;
                yy63:
                    ++YYCURSOR;
#line 93 "src/FuelScanner.r2c"
                    {
                        state.push(string_literal);
                        return (*yylval = yytext, FuelParser::token::Expression);
                    }
#line 374 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy65:
                    ++YYCURSOR;
                yy66 :
#line 94 "src/FuelScanner.r2c"
                {
                    return (*yylval = yytext, FuelParser::token::Expression);
                }
#line 380 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy67:
                    yych = *++YYCURSOR;
                    goto yy66;
                yy68:
                    yych = *++YYCURSOR;
                    goto yy59;
                yy69:
                    ++YYCURSOR;
#line 92 "src/FuelScanner.r2c"
                    {
                        state.push(embedded_statement);
                        return (*yylval = yytext, FuelParser::token::Expression);
                    }
#line 391 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy71:
                    ++YYCURSOR;
                    if (YYLIMIT <= YYCURSOR) YYFILL(1);
                    yych = *YYCURSOR;
                    if (yych <= '\n')
                    {
                        if (yych <= 0x00) goto yy73;
                        if (yych <= '\t') goto yy71;
                    }
                    else
                    {
                        if (yych != '\r') goto yy71;
                    }
                yy73 :
#line 89 "src/FuelScanner.r2c"
                {
                    continue;
                }
#line 405 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                }
#line 97 "src/FuelScanner.r2c"
            }
            else if (state.top() == string_literal)
            {

#line 414 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                {
                    unsigned char yych;
                    if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
                    yych = *YYCURSOR;
                    if (yych <= 0x1F)
                    {
                        if (yych <= '\n')
                        {
                            if (yych <= 0x08) goto yy83;
                            if (yych <= '\t') goto yy78;
                            goto yy80;
                        }
                        else
                        {
                            if (yych == '\r') goto yy78;
                            goto yy83;
                        }
                    }
                    else
                    {
                        if (yych <= '"')
                        {
                            if (yych <= ' ') goto yy78;
                            if (yych <= '!') goto yy83;
                        }
                        else
                        {
                            if (yych == '\\') goto yy81;
                            goto yy83;
                        }
                    }
                    ++YYCURSOR;
#line 104 "src/FuelScanner.r2c"
                    {
                        state.pop();
                        return (*yylval = yytext, FuelParser::token::Expression);
                    }
#line 440 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy78:
                    ++YYCURSOR;
                yy79 :
#line 105 "src/FuelScanner.r2c"
                {
                    return (*yylval = yytext, FuelParser::token::Expression);
                }
#line 446 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy80:
                    yych = *++YYCURSOR;
                    goto yy79;
                yy81:
                    ++YYCURSOR;
                    if ((yych = *YYCURSOR) == '.') goto yy84;
                yy82 :
#line 107 "src/FuelScanner.r2c"
                {
                    return (*yylval = yytext, FuelParser::token::Expression);
                }
#line 456 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                yy83:
                    yych = *++YYCURSOR;
                    goto yy82;
                yy84:
                    ++YYCURSOR;
#line 106 "src/FuelScanner.r2c"
                    {
                        return (*yylval = yytext, FuelParser::token::Expression);
                    }
#line 464 "E:/Programming/Projects/gitea/GameState/build/FuelScanner.cpp"
                }
#line 109 "src/FuelScanner.r2c"
            }

            assert(false);
        }
    }
} // namespace ehb
